version: '3.7'
services:
  pbrapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: pbrapp/api
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - postgres
  postgres:
    image: postgres:10.4
    container_name: "postgres"
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=api_pbr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Romao1988!
    ports:
      - "5432:5432"

 
 